export const VALIDATE_USER = "VALIDATE_USER";
export const USER_VALIDATED_SUCCESSFULLY = "USER_VALIDATED_SUCCESSFULLY";
export const USER_VALIDATION_FAILED = "USER_VALIDATION_FAILED";
export const REMEMBER_ME = "REMEMBER_ME";
export const SIGN_OUT_LOGGEDIN_USER = "SIGN_OUT_LOGGEDIN_USER";
