export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_UPDATED_SUCCESSFULLY =
  "[API_RESPONSE] PROFILE_UPDATED_SUCCESSFULLY";
export const PROFILE_UPDATION_FAILED = "[API_RESPONSE] PROFILE_UPDATION_FAILED";

export const USER_REGISTERED_SUCCESSFULLY =
  "[API_RESPONSE] USER_REGISTERED_SUCCESSFULLY";
export const USER_REGISTRATION_FAILED =
  "[API_RESPONSE] USER_REGISTRATION_FAILED";

export const LANGUAGES_LOADED_SUCCESSFULLY =
  "[API RESPONSE] LANGUAGES_LOADED_SUCCESSFULLY";
export const LANGUAGES_LOADED_FAILED = "[API RESPONSE] LANGUAGES_LOADED_FAILED";

export const PROFILE_STRUCTURE_LOADED =
  "[API RESPONSE] PROFILE_STRUCTURE_LOADED";
export const PROFILE_STRUCTURE_FAILED =
  "[API RESPONSE] PROFILE_STRUCTURE_FAILED";
